name: "test"
on:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Build Pre-Release
        run: dotnet build --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --version-suffix pre-${{ github.run_number }} src/
      - name: Run Unit Tests
        run: dotnet test --configuration Release src/Loki.Net.Tests/
      - name: Run Integration Tests
        run: dotnet test --configuration Release src/Loki.Net.IntegrationTests/
      
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
